### ISSUE TITLE
Mislabeled county.

### ISSUE THREAD

**Issue by mgasman** [jakobzhao/virus#26]
Orleans county in New York has information for Louisiana.

**Comment by jakobzhao** [comment]
fixed. thanks. This issue is closed.

**Comment by mgasman** [comment]
The map is still showing a cluster in UpState New York, west of Rochester,
in Orleans county - the details on this cluster all relate to the Louisiana
information (Orleans parish).

**Comment by mgasman** [comment]
The cluster with label  NO.1806-1813 is showing in New York, Orleans county
- It belongs in Louisiana.
